### ISSUE TITLE
java.lang.NoClassDefFoundError: org/eclipse/collections/api/map/primitive/MutableObjectIntMap

### ISSUE THREAD

**Issue by Lihengwannafly** [jelmerk/hnswlib#25]
I run hnswlib in spark, but this error occurs:
```
java.lang.NoClassDefFoundError: org/eclipse/collections/api/map/primitive/MutableObjectIntMap
        at com.github.jelmerk.knn.scalalike.hnsw.HnswIndex$.apply(HnswIndex.scala:108)
        at com.github.jelmerk.spark.knn.hnsw.HnswSimilarity.createIndex(HnswSimilarity.scala:150)
        at com.github.jelmerk.spark.knn.hnsw.HnswSimilarity.createIndex(HnswSimilarity.scala:132)
        at com.github.jelmerk.spark.knn.KnnAlgorithm$$anonfun$typedFit$1.apply(KnnAlgorithm.scala:796)
        at com.github.jelmerk.spark.knn.KnnAlgorithm$$anonfun$typedFit$1.apply(KnnAlgorithm.scala:786)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:925)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:925)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1964)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1964)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:325)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.eclipse.collections.api.map.primitive.MutableObjectIntMap
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

```

**Comment by jelmerk** [comment]
How are you referencing hnswlib ? if you use --packages it should work if you use --jars you would also need to include eclipse collections which is a transitive dependency of hnswlib. 

In general I would suggest using --packages

**Comment by tonight-is-you** [comment]
> How are you referencing hnswlib ? if you use --packages it should work if you use --jars you would also need to include eclipse collections which is a transitive dependency of hnswlib.
> 
> In general I would suggest using --packages

i run hnswlib in  java, and meet the same error as @Lihengwannafly, i am new to java, can you help to supply execute command ?(assume my jar file name: hnswlib-001.jar, class name: com.github.jelmerk.knn.hnsw.EmbText)
