### ISSUE TITLE
Not able to load persisted index

### ISSUE THREAD

**Issue by mlipkovich** [jelmerk/hnswlib#46]
Hello,

First of all thanks for the library! 
Can you please take a look into the following issue? When I try to load persisted index I'm getting the error below:
```
java.io.InvalidObjectException: ReflectiveOperationException during deserialization
  at java.base/java.lang.invoke.SerializedLambda.readResolve(SerializedLambda.java:280)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at java.base/java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1321)
  at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2251)
  at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742)
  at java.base/java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2584)
  at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2442)
  at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2242)
  at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742)
  at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:514)
  at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:472)
  at com.github.jelmerk.knn.hnsw.HnswIndex.readObject(HnswIndex.java:744)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1231)
  at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2408)
  at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2242)
  at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742)
  at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:514)
  at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:472)
  at com.github.jelmerk.knn.hnsw.HnswIndex.load(HnswIndex.java:867)
  at com.github.jelmerk.knn.hnsw.HnswIndex.load(HnswIndex.java:831)
  at com.github.jelmerk.knn.scalalike.hnsw.HnswIndex$.load(HnswIndex.scala:38)
  ... 36 elided
Caused by: java.lang.reflect.InvocationTargetException: java.lang.IllegalArgumentException: too many arguments
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at java.base/java.lang.invoke.SerializedLambda.readResolve(SerializedLambda.java:278)
  ... 63 more
Caused by: java.lang.IllegalArgumentException: too many arguments
  at java.base/java.lang.invoke.LambdaMetafactory.altMetafactory(LambdaMetafactory.java:511)
  at scala.runtime.LambdaDeserializer$.makeCallSite$1(LambdaDeserializer.scala:105)
  at scala.runtime.LambdaDeserializer$.deserializeLambda(LambdaDeserializer.scala:114)
  at scala.runtime.LambdaDeserialize.deserializeLambda(LambdaDeserialize.java:38)
  at com.github.jelmerk.knn.scalalike.package$.$deserializeLambda$(package.scala)
  ... 68 more

``` 

Here is a minimal code to reproduce the issue:
```
    import com.github.jelmerk.knn.scalalike._
    import com.github.jelmerk.knn.scalalike.hnsw._
    import java.io.File

    @SerialVersionUID(1L) case class Word(id: String, vector: Array[Float]) extends Item[String, Array[Float]]

    val hnswIndex = HnswIndex[String, Array[Float], Word, Float](floatCosineDistance, 10)
    hnswIndex.save(new File("./indexfile"))
    HnswIndex.load(new File("./indexfile"))
```

My sbt dependency:
```
"com.github.jelmerk" %% "hnswlib-scala" % "0.0.19",
```

Sbt version `1.3.3`, scala version `2.12.10`

**Comment by jelmerk** [comment]
Thats a very old version could you try version "0.0.49" instead

**Comment by jelmerk** [comment]
Also I found [this](https://github.com/scala/bug/issues/12419) , are you using jdk 17 ?

**Comment by mlipkovich** [comment]
Thanks for the quick response!

Updated the version - didn't help. 
Yes, I'm using jdk17

**Comment by jelmerk** [comment]
probably 2.12.15 would have worked too

**Comment by mlipkovich** [comment]
it works indeed. will proceed with `2.12.15`. thanks
