### ISSUE TITLE
Small number of queries succeeds, whereas larger number fails

### ISSUE THREAD

**Issue by alistairdivorty** [jelmerk/hnswlib#50]
I have used hnswlib-pyspark to index reference data consisting of ~200M rows. The PySpark code is running on Amazon EMR Serverless. I am able to obtain results for 10 rows of query data. If I increase the number of rows, however, to a greater number, such as 100, the outputted DataFrame is empty. If I attempt to use a saved version of the fitted model pipeline, the following exception is thrown by one or more executor nodes:

```
java.lang.IllegalStateException: Workers failed to complete.
	at com.github.jelmerk.spark.knn.KnnModelOps$$anon$2.hasNext(KnnAlgorithm.scala:596)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.shuffle.sort.UnsafeShuffleWriter.write(UnsafeShuffleWriter.java:183)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:133)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1474)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Configuration:**

```
BruteForceSimilarity(
    identifierCol=ref_identifier_col,
    queryIdentifierCol=query_identifier_col,
    featuresCol="features",
    distanceFunction="inner-product",
    k=10,
    numPartitions=30,
    numReplicas=2,
    excludeSelf=False,
    similarityThreshold=0.8,
    predictionCol="knn",
)
```

**Spark configuration**:

- `spark.emr-serverless.executor.disk` – 20g
- `spark.executor.instances` – 40
- `spark.dynamicAllocation.enabled` – false

I am seeking advice on possible causes of this issue.

Thank you very much.

**Comment by jelmerk** [comment]
BruteForceSimilarity does a pairwise comparison. It will compare each vector with 200M other vectors, which is going to be super slow and you should not use it on datasets of that size. Its really only intended to be used on small samples to benchmark the results produced by the approximative algorithm

**Comment by alistairdivorty** [comment]
> BruteForceSimilarity does a pairwise comparison. It will compare each vector with 200M other vectors, which is going to be super slow and you should not use it on datasets of that size. Its really only intended to be used on small samples to benchmark the results produced by the approximative algorithm

Thank you for the help @jelmerk. I'm now trying to construct an index using the `HnswSimilarity` estimator, so I can benchmark the accuracy against predictions generated for a small sample of the query data by the `BruteForceSimilarity` estimator. I'm finding that the last few tasks seem to run very long, despite previous tasks having completed rapidly.

![Screenshot 2022-08-08 at 13 15 26](https://user-images.githubusercontent.com/65289824/183416440-d9940c07-5531-4bfe-8304-125465906b8b.png)

![Screenshot 2022-08-08 at 13 25 39](https://user-images.githubusercontent.com/65289824/183417517-4f34136c-2daf-4f2c-b7bc-9a48001f5b0b.png)

Would you be able to shed any light on this? Thank you.

**Comment by jelmerk** [comment]
Please take a look at the  [suggested configuration](https://github.com/jelmerk/hnswlib/tree/master/hnswlib-pyspark#suggested-configuration)

For instance I noticed that have fewer partitions than executors. 
If with those settings it still does not behave as you expect then please grab all lines in the executor logs that contain "partition 00"

For example with
yarn logs -applicationId YOUR_APPLICATION_ID |  grep 'partition 00' > log.txt

and attach it to the issue

**Comment by jelmerk** [comment]
closing due to inactivity

**Comment by k4u5h1k** [comment]
Hey @jelmerk. I am getting this exact same error with HnswSimilarity during querying

My data is 8 million rows (about 50 gigs in size) and code is as follows
``` python3
normalizer = Normalizer(inputCol='emb_vector', outputCol='normalized_emb_vec')

hnsw = HnswSimilarity(identifierCol='id', featuresCol='normalized_emb_vec', distanceFunction='inner-product', m=48, ef=1000, k=1000,
                      efConstruction=200, queryIdentifierCol='id', numPartitions=50, excludeSelf=False)
```

I am using 50 executors with 10 cores each and 25 gigs of memory and all the correct suggested config on spark 2.4.
Package I am using is `com.github.jelmerk:hnswlib-spark_2.4_2.11:0.0.49`
